version: '3'
services:
  ipfs-public:
    image: node:10
    volumes:
      - ./storage-ipfs:/root/.jsipfs
      - ./init-and-daemon.sh:/opt/app/node_modules/ipfs/init-and-daemon.sh
      - ./config-nodejs.js:/opt/app/node_modules/ipfs/src/core/runtime/config-nodejs.js
    environment:
      - IPFS_API_HOST=127.0.0.1
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
  ipfs-private:
    image: node:10
    volumes:
      - ./private-storage-ipfs:/root/.jsipfs
      - ./init-and-daemon.sh:/opt/app/node_modules/ipfs/init-and-daemon.sh
      - ./private-config-nodejs.js:/opt/app/node_modules/ipfs/src/core/runtime/config-nodejs.js
    environment:
      - IPFS_API_HOST=127.0.0.1
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
networks:
  outside:
    external:
      name: "host"
