version: '3'
services:
  ipfs-dameon:
    image: watorvapor/js-ipfs-2
    volumes:
      - ./storage-ipfs:/root/.jsipfs
    networks:
      - outside
    expose:
      - '4004'
      - '4005'
      - '5003'
      - '9091'
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
networks:
  outside:
    external:
      name: "host"

