version: '3'
services:
  ipfs-dameon:
    image: watorvapor/js-ipfs-2
    volumes:
      - ./storage-ipfs:/root/.jsipfs
      - ./init-and-daemon.sh:/usr/src/app/init-and-daemon.sh
      - ./config-nodejs.js:/usr/src/app/src/core/runtime/config-nodejs.js
    environment:
      - IPFS_API_HOST=127.0.0.1
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
  ipfs-dameon-private:
    image: watorvapor/js-ipfs-2
    volumes:
      - ./private-storage-ipfs:/root/.jsipfs
      - ./init-and-daemon.sh:/usr/src/app/init-and-daemon.sh
      - ./private-config-nodejs.js:/usr/src/app/src/core/runtime/config-nodejs.js
    environment:
      - IPFS_API_HOST=127.0.0.1
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
  ipfs-dameon-pubsub-bug:
    image: watorvapor/js-ipfs-2
    volumes:
      - ./pubsub-bug-storage-ipfs:/root/.jsipfs
      - ./init-and-daemon.sh:/usr/src/app/init-and-daemon.sh
      - ./pubsub-bug-config-nodejs.js:/usr/src/app/src/core/runtime/config-nodejs.js
    environment:
      - IPFS_API_HOST=127.0.0.1
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
networks:
  outside:
    external:
      name: "host"

