version: '3'
services:
  cephfs-nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /watorvapor/cert:/etc/cert
      - /watorvapor/wai.storage/hashArchive:/hashArchive
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
  hash-public:
    image: node:lts
    volumes:
      - ./:/opt/app
      - /watorvapor/wai.storage/hashArchive:/watorvapor/wai.storage/hashArchive
    working_dir: "/opt/app"
    command: node ./hashAchhive.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
