version: '3'
services:
  ipfs-public:
    image: ipfs/go-ipfs:release
    volumes:
      - ./export-ipfs:/export
      - ./storage-ipfs:/data/ipfs
    command: daemon --migrate=true --enable-gc=true --offline
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '2.50'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 256M
  ipfs-nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /watorvapor/cert:/etc/cert
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
